# Generated by Django 4.2.2 on 2023-06-14 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0003_completedtest_delete_testgenerator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencepoints',
            name='User',
        ),
        migrations.AlterField(
            model_name='experiencepoints',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencepoints',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
