# Generated by Django 4.2.2 on 2023-06-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_statistics_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='percentage',
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_completed_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
