# Generated by Django 4.2.2 on 2023-06-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_remove_statistics_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='User',
            new_name='user',
        ),
    ]
