# Generated by Django 4.2.2 on 2023-06-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_rename_user_statistics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtest',
            name='test_alphabet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='test_family_friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='test_food_drinks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='test_numbers',
            field=models.BooleanField(default=False),
        ),
    ]
