# Generated by Django 4.2.2 on 2023-06-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_completedtest_test_alphabet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testalphabet',
            old_name='option3',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='testfamilyfriends',
            old_name='option3',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='testfooddrinks',
            old_name='option3',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='testnumbers',
            old_name='option4',
            new_name='answer',
        ),
    ]
