# Generated by Django 4.2.2 on 2023-06-15 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0013_alter_completedtest_test_alphabet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_correct_answer', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=255)),
                ('wrong_answer_1', models.CharField(max_length=255)),
                ('wrong_answer_2', models.CharField(max_length=255)),
                ('wrong_answer_3', models.CharField(max_length=255)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='experiencepoints',
            name='user',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testalphabet',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='testfamilyfriends',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='testfooddrinks',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='testnumbers',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='difficultylevel',
            name='level',
        ),
        migrations.AddField(
            model_name='difficultylevel',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.DeleteModel(
            name='CompletedTest',
        ),
        migrations.DeleteModel(
            name='ExperiencePoints',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='TestAlphabet',
        ),
        migrations.DeleteModel(
            name='TestFamilyFriends',
        ),
        migrations.DeleteModel(
            name='TestFoodDrinks',
        ),
        migrations.DeleteModel(
            name='TestNumbers',
        ),
        migrations.AddField(
            model_name='testtype',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.difficultylevel'),
        ),
        migrations.AddField(
            model_name='test',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.difficultylevel'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testtype'),
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerstatistic',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test'),
        ),
        migrations.AddField(
            model_name='answerstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
