# Generated by Django 4.2.2 on 2023-06-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_testtype_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerstatistic',
            name='test',
        ),
    ]
