# Generated by Django 4.2.2 on 2023-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_remove_testtype_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
