# Generated by Django 4.2.2 on 2023-06-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_level_question_user_points_user_statistic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.testtype'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.CharField(default='вариант', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(default='вариант', max_length=200),
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.testtype')),
            ],
        ),
    ]
