# Generated by Django 4.2.2 on 2023-06-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_question_test_type_alter_question_choice1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtype',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.level'),
        ),
    ]
