# Generated by Django 4.2.2 on 2023-06-16 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_testing_test_type_testing_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.question'),
        ),
    ]
