# Generated by Django 4.2.2 on 2023-06-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_testing_is_correct_testing_user_testing_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testing',
            name='statistic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testing',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
